baseURL = "https://ewen.io"
languageCode = "en-us"
title = "ewen"
titleCaseStyle = "AP"
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true
ignoreFiles = ['\.Rmd$', '_files$', '_cache$', '\.knit\.md$', '\.utf8\.md$']

[taxonomies]
tag = "tags"

[permalinks]
posts = ":title"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = false
angledQuotes = false

[params]
timeFormatRFC3339 = "2006-01-02T15:04:05Z07:00"
timeFormatDefault = "January 2, 2006"
timeFormatShort = "Jan 02, 2006"
description = "you alright, mate?"

[params.author]
name = "ewen"
homepage = "https://ewen.io"

# twitterHandle = "ewen_"
[menu]

[[menu.main]]
name = "about"
weight = 1
url = "/about"

[[menu.main]]
name = "privacy"
weight = 2
url = "/privacy"

[[menu.footer]]
name = "RSS"
weight = 3
url = "/index.xml"

[[menu.footer]]
name = "email"
weight = 4
url = "mailto:ewenme@tutanota.com"

[[menu.footer]]
name = "github"
weight = 5
url = "https://github.com/ewenme"

[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "keywords"
weight = 80

[markup]

[markup.goldmark]

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false
